### ISSUE TITLE
Congratulations, Jacob!

### ISSUE THREAD

**Issue by javs-perez** [JacobMillward/millward-yuan-wedding#1]
Jacob - congratulations to you and Jianan! I wish you both lots of happiness and success in your next chapter together! 

\- Johanan

--------------------------------------------------------
Hey Jacob,

Hope you're enjoying the new job, and congrats on the engagement! Wishing you a happy future. 

\- Cedric

--------------------------------------------------------

Hi Jacob,

Hello from the (2nd) newest member of Javi's team! Congratulations on this milestone, and wishing you and Jianan a lifetime of happiness! 

\- Maggie

--------------------------------------------------------

Congratulations, Jacob and Jianan! Wishing you both a lifetime filled with joy, love, and endless adventures together. May your journey ahead be as beautiful and exciting as your wedding day. Sending you warmest wishes for a happy and prosperous future. Cheers to love and togetherness! 

\- Kamil

--------------------------------------------------------

Hey Jacob and Jianan,

Big congrats on the upcoming wedding! It feels like just yesterday Jacob was part of our team, and now you are celebrating this awesome new chapter in your lives.

We're all sending you lots of good vibes and well wishes as you embark on this journey together. It's not just about the big moments but all the small, everyday ones that you'll share, and we couldn't be happier for you both.

Here's to a future filled with love, laughter, and all the happiness in the world. Can't wait to hear about all the adventures you two will have together.

Cheers to a beautiful life ahead,

\- Javi

**Comment by easyt** [comment]
Congrats to you both 🎉

**Comment by JacobMillward** [comment]
Thanks from us both! ☺️

Great to get visibility on this issue, I'll make sure to get this resolved soon. Current ETA is 16th November release for this feature 🎉

**Comment by JacobMillward** [comment]
Feature released as of yesterday!

Thanks so much again for the well wishes. I'm a Millward-Yuan now!

**Comment by javs-perez** [comment]
❤

**Comment by jidicula** [comment]
🎊
